language: cpp
python:
- '3.4'
git:
  depth: 1000
os:
- linux
dist: trusty
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
      secure: "QRu1PwMzY8SqFSE1e6g4nl74MFtWh9uhAgq00C2eSUWG4giWAGqXVcZKAlwsPt7F21vTUsY4lK7xfQVIQgIVdq+MH4E0mq6SW28QWmHghM28FTqOtY0GdhQ5PwHhcYbUasJrcw9/uPwtRDiBHRj+E/NbXZ6jdnsww/vvwV7+vGtiOVWhzEYrDX/XlaLxiHjyZ8ggtfFFUKbQ1erHhzpxQsnGvVqG9b2wvwYswEaHevcBr41OClvzjl86VLPAMweUx+b1VaO8edxD8jnj8kEcfL87g4MyWCmU2+YIUb1iie1dunfv2yZPGOkWoc+5P5BVFzo7z8f7ILnNvIkwRfIyhMsaYfefGcLcAoQ8W2tAqaXsc2sK4Q28i11BX/LcqzW/mhrvHZiEMEjyxr2bAL0yzmvJ/7f31R8CXAph/fpo6kIwdDFbQOgWIXp9Ers4f6qc704LwOlR8js8gokEZ7yVDFuSdi0fQMUl1851KQMdv3gbcxDiE34Z+eFVqenAkZHOnYsd2oERtv0XizTa8yMy2J9hIcP6E5m6DKRyLTsze2xW9Z9PpKDH4QQrkXwEoUyV9oj/IW95iu9SMXdOZgWXLPhfflqOyG9jizWA347LVOwc7ApZ1X1HEVpSR6HKy2UNSfD2zLpd9g/dRXvMp8Z9UHTRje4HYkgQQ7qv/sR6S48="

script: echo Build Done
