language: cpp
python:
- '3.4'
git:
  depth: 1000
os:
- linux
dist: trusty
notifications:
  webhooks:
    urls:
      - secure: H4Fn56K0giOCteG3+kI/mU426t7/3j5yT3UEoRHk9UqPds2yym2FR9xvHB0Y+zTdGkBTK6aol8pvz6GXCZNjl8QwNRqNHLGfvkrHk+rDbhCb4cqB374ble06kXbhfSgKn1nO/eURIkJW9N49CqHhYNSBldTj1TF8DIBhgSpGKX09Tpyy4EjK0NQAOwCZxmGCPaFMzzJcRJwpZ4y0tC7dNNejtiHpxwe7Iu+tgfksnLqEXO7uWHysmTk/MIvEq6h0IvzfvTCLR5lzlbsOCo9o7HO+EhcPx+YylOXqG4BJfTW2W7lSKSH0Q6mBZncE2QTbNAfaf0odiOJNOrlrCZ3t81rxMj+GCvKOIeNhQP9+eUCZzruB6wpfwVrWlPYblwqBdWhhMXWjwJ430xViu9t/U/V5XSE2h+MN4Dao/4+/XewzudqSkUnb+UU3bkX+luzXoQMRN5AEvW5tLVn+TJAKDapgbAbT1VFHsCeJFa/8xX1Fktb4sTsX4qcxGonIXsaFSRZgwTfzNITX+b5DpTwatmBfXLiYW1Oi28mAO/6gABnIMx8OX0l4ECp+UiAB0xOihLG1gCeuDIjEuvDi/A4V1MiuiTdxdfSjP2Yb8DsyDNQYq+fDes1D6va79kTP2EUE2+n9dbasz94NmHlZ1EKV/57xO3snN8F1NJR+BTcmxFA=
    on_success: always
    on_failure: always
    on_start: always
script:
- echo Build Done
