language: cpp
python:
- '3.4'
git:
  depth: 1000
os:
- linux
dist: trusty
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
      secure: GJ0nmwBUkKMTzxz09BVX5Zy6O/pNPuX0tM4EQ3cbsQ5EeDll5+EP7y6UZBqIEdXGEzXI39ZctGaURvIv+HUzg5IqB2it5Z8LOG9C5ji/5RixTjEUHrK5D+j7fyarM3rkY4qhfW36EPJC0hED0c9nIlfXjf3g07wKarvb27j3CTxNhOv1BeX1B8xkwF+RuaJPwAFKQsrGOun9eS9fIUHtuflfFIvqWNV1VrNzfbvAs5Sr+qLrWXb0LAIKFJwffXVJPV9RHhXQE9JejbGijUUQIqXdNkZXdz5oqz9r5MyhhxMDGYRKVp3zhywoYpgk7JajSEQr9AWs2gLz6NJN59I2BOrh6CTJjRXMZDkAT15uPPEgDZERZBWyvqBZq7WBXZPSCdeI165B5EunEC/virh5GDpGm/knl6MsZ+sLi5Z1DIW/qEJB/ByeR3TK4cC6UR1idgdxpFzg33c1yKh8KczMo/UFZhuON7XwMWLQ/b4VQNkW7KD4IjbchIBAF7X1fln6reee3jJBVfdw5TP1emdueRBIEz3HrfzwDb3o21hEOADATh0BcZCSeXGF+KL3X7mU7Z9XJIeym0KpbfjOK8hgoK2UhR6xrjEUN+E6IobXxHUnwg8Q6kv6OsZ3ggIvgWCONGhGuTsxYsSkoRxlEGzBuWD1gbEASfeOnLE4bSjg5m4=
script: echo Build Done
